### ISSUE TITLE
🐞[BUG] mining claims: "cannot find city ID for city"

### ISSUE THREAD

**Issue by whoabuddy** [boomcrypto/citycoins-ui#3]
**Describe the bug**
Seeing a few reports in Discord on this one:

> Attempted to get mining rewards and got “Cannot find city ID for city.” Didn’t see many posts on it, any workarounds to claim citycoins? I am showing 100 blocks have passed too (BabyGotStacks#1157)

> I'm having a hard time claiming MIA blocks that have been won. I've logged out, cleared cache etc. Am I in the wrong spot? Feeling like I'm missing something really simple.
> I'm getting the same error "Cannot find City ID" on MineCityCoins. I do have MIA selected.
> I've been able to claim via the sandbox in the meantime - user error?
> More so asking in case it may help others having the same woes. (Coin Latifah#2691)

> I won the some blocks how to get a mia?? (Luckyboy#7897)

![image0](https://user-images.githubusercontent.com/9038904/222792307-3cc59bb3-5790-4663-bf1a-b82afbd6e36a.jpg)

![image0](https://user-images.githubusercontent.com/9038904/222792322-dd5d3c42-c7f6-43d8-a257-912f1a279ef9.jpg)

**To Reproduce**

TBD - need to evaluate against block heights being claimed. The city ID mentioned above is only relevant to the DaoV1 contracts and should not be checked for LegacyV1/LegacyV2.

**Expected behavior**

The mining claim will call the correct contract based on block height.

**Comment by Luckyboy4** [comment]
This means do i have to wait to fix??

**Comment by whoabuddy** [comment]
Current fix for testing is below, once confirmed can be merged.

https://fix-mining-claims.citycoins-ui.pages.dev/
